CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','support','user') NOT NULL DEFAULT 'user',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS technicians (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(32) NOT NULL UNIQUE,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sectors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(32) NULL,
  email VARCHAR(190) NULL,
  address VARCHAR(255) NULL,
  description TEXT NULL,
  created_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sector_user (
  sector_id INT NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (sector_id, user_id),
  FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS companies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS breakdowns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sector_id INT NOT NULL,
  company_id INT NULL,
  technician_id INT NULL,
  technician_required TINYINT(1) NOT NULL DEFAULT 0,
  contact_phone VARCHAR(32) NULL,
  system_name VARCHAR(190) NOT NULL,
  description TEXT NULL,
  occurred_at DATETIME NOT NULL,
  fixed_by VARCHAR(150) NOT NULL,
  client_name VARCHAR(150) NOT NULL,
  status ENUM('open','in_progress','fixed') NOT NULL DEFAULT 'open',
  note TEXT NULL,
  created_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (sector_id, occurred_at),
  FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS breakdown_technicians (
  breakdown_id INT NOT NULL,
  technician_id INT NOT NULL,
  PRIMARY KEY (breakdown_id, technician_id),
  FOREIGN KEY (breakdown_id) REFERENCES breakdowns(id) ON DELETE CASCADE,
  FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS edit_locks (
  resource_type VARCHAR(32) NOT NULL,
  resource_id INT NOT NULL,
  owner_session VARCHAR(128) NOT NULL,
  owner_name VARCHAR(120) NOT NULL,
  token CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (resource_type, resource_id),
  INDEX (expires_at)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS machine_tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kind ENUM('category','brand','model') NOT NULL,
  name VARCHAR(120) NOT NULL,
  UNIQUE KEY kind_name (kind, name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS machines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(120) NOT NULL,
  brand VARCHAR(120) NOT NULL,
  model VARCHAR(120) NOT NULL,
  model_code VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
